"""
Assembles web/data.js from the individual web/data/*.json files so the page
keeps working from a plain file:// path with zero fetch() calls (same
approach as before, just with more datasets inlined now).
"""
import json

DATA_DIR = r"C:\Users\Anusorn.s\OneDrive - CAAT\Documents\2026\Project\ThaiBirdStrikeGIS\web\data"
OUT = r"C:\Users\Anusorn.s\OneDrive - CAAT\Documents\2026\Project\ThaiBirdStrikeGIS\web\data.js"


def load(name):
    with open(f"{DATA_DIR}\\{name}", encoding="utf-8") as f:
        return json.load(f)


def main():
    airports = load("airports.json")
    density = load("heatmap_density.json")
    by_month = load("heatmap_by_month.json")
    stats = load("airport_stats.json")
    landuse = load("landuse.json")
    attractors = load("attractors.json")

    def j(obj):
        return json.dumps(obj, ensure_ascii=False, separators=(",", ":"))

    parts = [
        "// AUTO-GENERATED by data_prep/build_data_js.py — do not edit by hand.",
        "// Inlined as JS (not fetch()) so the page works when opened directly as",
        "// a local file:// (no server needed).",
        "",
        "// AIRPORTS: public ARP coordinates + longest-runway bearing from OurAirports.org",
        "// (public domain), except BTZ (Betong/VTSY) which is verified against the real",
        "// AIP Thailand eAIP AD 2.12 page (aip.caat.or.th).",
        f"var AIRPORTS = {j(airports)};",
        "",
        "// HEATMAP_DENSITY: [lat, lon, count, damageWeight] per ~300m grid cell, all-time,",
        "// all 43 airports (only 34 have any recorded incidents in the source workbook).",
        "// Estimated positions from FlightPhase+Altitude, NOT real GPS fixes — see README.",
        f"var HEATMAP_DENSITY = {j(density)};",
        "",
        "// HEATMAP_BY_MONTH: same grid format, keyed \"YYYY-MM\", 2021-01..2025-12.",
        f"var HEATMAP_BY_MONTH = {j(by_month)};",
        "",
        "// AIRPORT_STATS: per-airport aggregate (total incidents, most common flight",
        "// phase, peak month, damage rate). Airports absent here have zero recorded",
        "// incidents in the source workbook (not necessarily zero real strikes).",
        f"var AIRPORT_STATS = {j(stats)};",
        "",
        "// LANDUSE: OSM landfill/wetland/nature_reserve centroids within 15km of any",
        "// airport (Overpass API, ODbL). Centroid points, not full polygons.",
        f"var LANDUSE = {j(landuse)};",
        "",
        "// ATTRACTORS: named LANDUSE features within 15km of the 6 highest-incident",
        "// airports — candidate wildlife-attractor sites worth flagging.",
        f"var ATTRACTORS = {j(attractors)};",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print("Wrote", OUT, f"({sum(len(p) for p in parts)} chars)")


if __name__ == "__main__":
    main()
